### ISSUE TITLE
Problematic bypass in the magic function

### ISSUE THREAD

**Issue by Ascentus** [littlesera/LSCG#332]
Dear developers of the LSCG plugin, 

I want to first express my gratitude for your wonderful work. The new version of the LSCG plugin added a great variety of interesting possibilities to the game. However, I feel it necessary to report some problematic uses of the magic function. It, under the default settings, seems to be maliciously exploited by some players, bypassing the consent of sharing remote access, allowing them to gain full access to the victim, and disabling the safeword and private message function for an infinite timespan, ultimately ruining the game under any difficulty level. This damages the consensual basis of the BC environment and poses a huge threat to players’ experience. Therefore, we’d like to ask if the developers of the plugin could please kindly check the function; we would assist the process with any chat log required.

**Comment by littlesera** [comment]
LSCG Remote Access shouldn't allow changing vanilla BC settings. It has also removed the 'character access' block that would prevent reaching the safeword button, and activating safeword should remove any LSCG states. At least by design unless there is a bug. Do you have a specific example of this malicious activity?

In my testing gagged and sleeping states (for example) still allow whispers and beeps, and my test character can still get to their safeword button via the character actions dialog.

By default, spell effects will also only be active for a set amount of time generally ranging from 5min - 2hours.
Also by default 'Remote Access' to LSCG settings is disabled for all sections, including magic.
Are malicious players forging LSCG system beep packets to spoof remote access?

**Comment by Ascentus** [comment]
There is no packet found. Double-checked with the victim, the following was the specific case:

The player cast a petrification on the victim, which restrained the ability to speak or move, and an icon of the magic was shown on the character. In the end, the effect was removed by dispelling. However, the time span of the spell was marked 0 minutes, for which the scale by the icon did not seem to change through time. Does the 0-minute duration mean a 2-hour maximum or infinity?

**Comment by Ascentus** [comment]
There is no packet found. Double-checked with the victim, the following was the specific case:

The player cast a petrification on the victim, which restrained the ability to speak or move, and an icon of the magic was shown on the character. In the end, the effect was removed by dispelling. However, the time span of the spell was marked 0 minutes, for which the scale by the icon did not seem to change through time. Does the 0-minute duration mean a 2-hour maximum or infinity?

**Comment by littlesera** [comment]
If there's no little bar that would indicate that the player's "Limited Spell Duration" option in LSCG Magic settings is unchecked. This setting is checked by default, though it is a configurable option for other people if "Remote Access" is also granted.

Even while petrified, the safeword button should be available and working in addition to the "/safeword" command. While normal speaking is blocked while petrified, OOC speech and whispering should still be allowed.

**Comment by littlesera** [comment]
The "0 minutes" text looks like a visual bug when "Limited Spell Duration" is disabled.

**Comment by Ascentus** [comment]
Understood. Thank you very much.
