### ISSUE TITLE
Overlay icon is buggy.

### ISSUE THREAD

**Issue by dDeepLb** [littlesera/LSCG#40]
Sometimes I don't see it, but after reload it appears. Sometimes I don't see it, and ever reload doesn't help.

**Comment by littlesera** [comment]
More details and/or screengrabs are needed. Is this on your own character? Is LSCG properly loading? (check for "Player.LSCG" in the console if you have access)
Are these other characters? It'll only appear if those characters are using the mod and have refreshed since this change went in. If you are ghosting them or have your icon state partially/fully hidden, it will also not display any overlay icon.

**Comment by littlesera** [comment]
I'm unable to reproduce it with my test accounts. If you continue to see it try and get a reliable set of steps that recreates the issue.
