### ISSUE TITLE
Increase Limited amount of Suggestion

### ISSUE THREAD

**Issue by KuraikoKooriookami** [littlesera/LSCG#543]
I was curious if it would be possible to increase the maximum amount of Suggestions, 
I kinda hit a limit as a friend of mine couldn't add another suggestion on me.

**Comment by littlesera** [comment]
0_0
the current limit is 64, how many do you expect to want?
Indefinite isn't possible as it could overflow the allowed extension storage data.

**Comment by dDeepLb** [comment]
> 0_0 the current limit is 64, how many do you expect to want? Indefinite isn't possible as it could overflow the allowed extension storage data.

local storage^^ and could allow exporting and importing everything from there. or maybe save data to file and allow load it?

**Comment by littlesera** [comment]
local storage isn't a good solution for anyone using incognito browser tabs

**Comment by KuraikoKooriookami** [comment]
how about 128? as far as i believe on how 64 got choosen as a limit it would be just one bit more. 
Otherwise sounds 100 as a user view as a good number.

**Comment by dDeepLb** [comment]
> local storage isn't a good solution for anyone using incognito browser tabs, and saving to a file on disk is dangerous for a web script to do.

but there's already scripts that do that. EBCH for example.

**Comment by littlesera** [comment]
@KuraikoKooriookami - It's not a bitwise issue, but the total bytes size of the settings json object. Suggestions are less an issue than spells because of the potential for large outfit/polymorph strings.

@dDeepLb - EBCH uses indexedDB, which does allow larger storage locally (great for something indeterminantly large like chat logs), but is not accessible across browsers or if you switch machines (bad for things like configuration/profile settings). ECBH only uses it for the chat logs, and still stores user settings in Player.OnlineSettings

**Comment by littlesera** [comment]
Increased to 100 for now

**Comment by KuraikoKooriookami** [comment]
Thank you very much~
