### ISSUE TITLE
When I have dildo in my hands, it says rub with penis

### ISSUE THREAD

**Issue by dDeepLb** [littlesera/LSCG#55]

**Comment by littlesera** [comment]
Not sure where you're seeing this. Can you elaborate/attach a screen grab?

**Comment by dDeepLb** [comment]
![image](https://github.com/littlesera/LSCG/assets/71733861/5ea96f07-3525-4cd5-b48c-d98c6ec6af14)
Alsp would be good if you can use dildo on you in some cases like rub or slap.

**Comment by littlesera** [comment]
Ah I see, it's because the custom action is hard coding "penis" in the activity, where the dildo and an actual 'penis' boty have "PenetrationItem" properties. Try reproducing with a nude male, you should see something like:
![image](https://github.com/littlesera/LSCG/assets/126942824/b58dc70c-2c4e-409d-b7cc-9696a2fb42bb)

This means you can use the dildo in all the same 'rub/slap' spots already, but seems only if you also have a penis. This looks tricky and needs some careful investigation.
